node_type: eagerx_dcsc_setups.nodes/ButterworthFilter
default:
  rate:
  inputs: [signal]
  outputs: [filtered]
  process: 0  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'
  color: magenta
  log_level: 30  # {0: SILENT, 10: DEBUG, 20: INFO, 30: WARN, 40: ERROR, 50: FATAL}
  N: 2 # The order of the filter.
  Wn: 1 # The critical frequency or frequencies.
  btype: lowpass # {lowpass, highpass, bandpass, bandstop}

inputs:
  signal:
    msg_type: std_msgs.msg/Float32MultiArray
    window: $(default N)
    converter:
      converter_type: eagerx_dcsc_setups.converters/GetIndex
    space_converter:
      converter_type: eagerx_bridge_ode.converters/Space_RosFloat32MultiArray
      low: [ -3 ]
      high: [ 3 ]

outputs:
  filtered:
    msg_type: std_msgs.msg/Float32MultiArray
