node_type: eagerx_bridge_real.simnodes/Render
default:
  rate:
  inputs: [tick]
  outputs: [image]
  process: 0  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'
  shape: [480, 480]
  camera_idx: 0

inputs:
  tick:
    msg_type: std_msgs.msg/UInt64
    window: 0

outputs:
  image:
    msg_type: sensor_msgs.msg/Image
