version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "bheijden"
    commit_message:
      prefix: "chore"
      include_scope: true
