# Always validate all commits, and ignore the PR title
commitsOnly: true

# Require at least one commit to be valid
# this is only relevant when using commitsOnly: true or titleAndCommits: true,
# which validate all commits by default
anyCommit: true
