# Always validate the PR title AND all the commits
titleAndCommits: true

# Do not require at least one commit to be valid
# this is only relevant when using commitsOnly: true or titleAndCommits: true,
# which validate all commits by default
anyCommit: false
