node_type: eagerx_bridge_test.bridge/TestBridgeNode
default:
  rate:
  outputs: [tick]
  states: [param_1]
  process: 0  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxbridge.launch'
  color: magenta
  log_level: 10  # {0: SILENT, 10: DEBUG, 20: INFO, 30: WARN, 40: ERROR, 50: FATAL}
  is_reactive: True
  real_time_factor: 0  # 0 == as fast as possible
  simulate_delays: True  # Whether to simulate the delay
  num_substeps: 10
  nonreactive_address: '/nonreactive_input_topic'  # Only required to test nonreactive inputs

outputs:
  tick:
    msg_type: std_msgs.msg/UInt64

states:
  param_1:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_bridge_test.converters/Space_RosUInt64
      dtype: uint64
      low: [0]
      high: [100]