node_type: eagerx_bridge_test.nodes/ProcessNode
default:
  rate:
  inputs: [tick, in_1, in_2, in_3]
  outputs: [out_1]
  process: 2  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'
  test_arg: 'TEST ARGUMENT'

inputs:
  tick:
    msg_type: std_msgs.msg/UInt64
    window: 0
  in_1:
    msg_type: std_msgs.msg/UInt64
    window: 0
  in_2:
    msg_type: std_msgs.msg/UInt64
    window: 0
  in_3:
    msg_type: std_msgs.msg/String
    window: 0

outputs:
  out_1:
    msg_type: std_msgs.msg/UInt64