node_type: eagerx_bridge_test.nodes/ProcessNode
default:
  rate:
  inputs: [tick, in_1]
  outputs: [out_1]
  states: []
  process: 2  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'
  test_arg: 'TEST ARGUMENT'

inputs:
  tick:
    msg_type: std_msgs.msg/UInt64
    window: 0
  in_1:
    msg_type: std_msgs.msg/UInt64
    window: 0

outputs:
  out_1:
    msg_type: std_msgs.msg/UInt64

states:
  state_1:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_bridge_test.converters/Space_RosUInt64
      dtype: uint64
      low: [0]
      high: [100]