default:
  sensors: [N6, N7]
  actuators: [ref_vel]
  states: [N9, N10]
  position: [0, 0, 0]
  orientation: [0, 0, 0]
  string: 'asdfasd'
  test_string: $(default string)
  test_list: $(default orientation)
  low: 0

#########################
## Agnostic definition ##
#########################
sensors: # inputs of env
  N6:
    rate: 15
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_bridge_test.converters/Space_RosUInt64
      dtype: uint64
      low: [0]
      high: [100]
  N7:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_bridge_test.converters/Space_RosUInt64
      dtype: uint64
      low: [0]
      high: [100]

actuators: # outputs of env
  N8:
    rate: 15
    msg_type: std_msgs.msg/String
    space_converter:
      converter_type: eagerx_bridge_test.converters/Space_RosString
      dtype: uint64
      low: $(default low)
      high: 100
      shape: [1]  # optional
  ref_vel:
    rate: 1
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_bridge_test.converters/Space_RosUInt64
      dtype: uint64
      low: [0]
      high: [100]

states:  # reset states inside bridge
  N9:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_bridge_test.converters/Space_RosUInt64
      dtype: uint64
      low: [0]
      high: [100]
  N10:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_bridge_test.converters/Space_RosUInt64
      dtype: uint64
      low: [0]
      high: [100]

#########################
### Engine definition ###
#########################
eagerx_bridge_test/bridge:
  urdf: $(find interbotix_xsarm_descriptions)/urdf/vx300s.urdf.xacro
  sensors:
    N6:
      node_config: eagerx_bridge_test/sim_sensor # These nodes cannot have an internal state
      states: [state_1]
      inputs: {in_1: $(ns env_name)/nonreactive_input_topic}  # $(ns env_name) is replaced at run-time with environment name
      outputs: [out_1] # Mapping of sensor output to sim_sensor output cname inside node_config "sim_sensor.yaml"
      color: cyan
      log_level: 10  # {0: SILENT, 10: DEBUG, 20: INFO, 30: WARN, 40: ERROR, 50: FATAL}
      nonreactive_rates: {in_1: 20}  # If input name (in_1) is listed as nonreactive, environment namespace will not be automatically prepended.
      process: 2  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
      test_arg: $(default test_string)
    N7:
      node_config: eagerx_bridge_test/sim_sensor # These nodes cannot have an internal state
      inputs: {in_1: $(ns obj_name)/sensors/N6}  # $(obj_name) is replaced at run-time with object name
      outputs: [out_1] # Mapping of sensor output to sim_sensor output cname inside node_config "sim_sensor.yaml"
      color: cyan
      process: 0  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
      test_arg: 'CHANGED ARGUMENT'

  actuators:  # Inputs as defined above
    N8:
      node_config: eagerx_bridge_test/sim_actuator
      inputs: {in_3: , # actuator input mapping to sim_node input name inside node_config "sim_actuator.yaml"
               in_2: $(ns obj_name)/sensors/N6}  # The $(ns obj_name) is prepended to reactive (simnode) inputs.
      color: green
      log_level: 10  # {0: SILENT, 10: DEBUG, 20: INFO, 30: WARN, 40: ERROR, 50: FATAL}
      process: 2  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
#      input_converters:  # can only contain converters for inputs other than "actuator input" ("in_1" in this case)
#        in_3:
#          converter_type: eagerx_bridge_test.converters/StringUInt64
#          test_arg: 'test'
      test_arg: 'CHANGED ARGUMENT'
    ref_vel:
      node_config: eagerx_bridge_test/sim_actuator
      inputs: {in_1: , # actuator input mapping to sim_node input name inside node_config "sim_actuator.yaml"
               in_2: $(ns obj_name)/sensors/N6}  # The $(env_name) is prepended to reactive (simnode) inputs.
      color: green
      process: 2  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
      test_arg: 'CHANGED ARGUMENT'
  states:
    N9:
      state_type: eagerx_bridge_test.simstates/TestSimState
      test_arg: 'CHANGED ARGUMENT'

    N10:
      state_type: eagerx_bridge_test.simstates/TestSimState
      test_arg: 'CHANGED ARGUMENT'

