#!/usr/bin/env python3

from __future__ import print_function

import rospy
import eagerx_core
from eagerx_core.bridge import RxBridge

if __name__ == '__main__':

    rospy.init_node('bridge', log_level=rospy.INFO)

    message_broker = eagerx_core.RxMessageBroker(owner=rospy.get_name())

    pnode = RxBridge(name=rospy.get_name(), message_broker=message_broker)

    message_broker.connect_io()

    pnode.node_initialized()

    rospy.spin()