#!/usr/bin/env python3

from __future__ import print_function

import rospy
import eagerx_core
from eagerx_core.node import RxNode

if __name__ == '__main__':

    rospy.init_node('process')

    message_broker = eagerx_core.RxMessageBroker(owner=rospy.get_name())

    pnode = RxNode(name=rospy.get_name(), message_broker=message_broker)

    message_broker.connect_io()

    pnode.node_initialized()

    rospy.spin()
