node_type: eagerx_core.basenode/ProcessNode
default:
  rate:
  inputs: [in_1]
  outputs: [out_1]
  states: [state_1]
  process: 1  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'
  test_arg: 'TEST ARGUMENT'

inputs:
  in_1:
    msg_type: std_msgs.msg/UInt64
    repeat: all
    space_converter:
      converter_type: eagerx_core.baseconverter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]
  in_2:
    msg_type: std_msgs.msg/UInt64
    repeat: all
    space_converter:
      converter_type: eagerx_core.baseconverter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]

outputs:
  out_1:
    msg_type: std_msgs.msg/UInt64
    start_with_msg: True
    space_converter:
      converter_type: eagerx_core.baseconverter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]
  out_2:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.baseconverter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]

states:
  state_1:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.baseconverter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]
  state_2:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.baseconverter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]