node_type: eagerx_core.rxnode/ProcessNode
default:
  rate:
  inputs: [tick, in_1]
  outputs: [out_1]
  states: []
  single_process: True
  launch_locally: True
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'
  test_arg: 'TEST ARGUMENT'

inputs:
  tick:
    msg_type: std_msgs.msg/UInt64
    repeat: all
  in_1:
    msg_type: std_msgs.msg/UInt64
    repeat: all

outputs:
  out_1:
    msg_type: std_msgs.msg/UInt64

states:
  error:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]