node_type: eagerx_core.node/ProcessNode
default:
  rate:
  inputs: [tick, action_1, action_2]
  outputs: [action_1]
  single_process: True
  launch_locally: True
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'
  test_arg: 'TEST ARGUMENT'

inputs:
  tick:
#    address: bridge/outputs/tick
    msg_type: std_msgs.msg/UInt64
    repeat: all
  action_1:
    msg_type: std_msgs.msg/UInt64
    repeat: all
  action_2:
    msg_type: std_msgs.msg/UInt64
    repeat: all

outputs:
  action_1:
    msg_type: std_msgs.msg/UInt64