#!/usr/bin/env python3

# ROS packages required
import rospy
from eagerx_core.core import RxBridge, RxNode, RxObject, EAGERxEnv
from eagerx_core.utils.node_utils import configure_connections, launch_roscore
from eagerx_core.constants import process

if __name__ == '__main__':
    roscore = launch_roscore()  # First launch roscore

    rospy.init_node('eagerx_core', anonymous=True, log_level=rospy.INFO)

    # Define nodes
    # todo: Create pid node (.yaml, .py)
    # todo: Create classifier node (.yaml, .py)
    # pid = RxNode.create('pid', 'eagerx_node_pid', 'process', rate=1.0, process=process.NEW_PROCESS)

    # Define object
    pendulum = RxObject.create('pendulum', 'eagerx_object_pendulum', 'pendulum', sensors=['pos_vel', 'image'])

    # Define action/observations
    actions, observations = EAGERxEnv.create_actions(), EAGERxEnv.create_observations()

    # Define render (optional)
    render = EAGERxEnv.create_render(display=False)

    # Connect nodes
    connections = [{'source': (pendulum, 'sensors', 'pos_vel'), 'target': (observations, 'pos_vel'), 'delay': 0},
                   {'source': (actions, 'torque'),              'target': (pendulum, 'actuators', 'torque'), 'delay': 0},
                   {'source': (pendulum, 'sensors', 'image'),   'target': (render, 'inputs', 'image')}
                   ]
    configure_connections(connections)

    # Define bridge
    bridge = RxBridge.create('eagerx_bridge_openai_classic_control', 'openai_bridge', rate=20, process=process.NEW_PROCESS, is_reactive=True, real_time_factor=0)

    # Initialize Environment
    env = EAGERxEnv(name='rx',
                    rate=20,
                    actions=actions,
                    observations=observations,
                    bridge=bridge,
                    nodes=[],
                    objects=[pendulum],
                    render=render,
                    )

    # First reset
    obs = env.reset()
    env.render(mode='human')
    for j in range(20):
        print('\n[Episode %s]' % j)
        for i in range(200):
            action = env.action_space.sample()
            obs, reward, done, info = env.step(action)
        obs = env.reset()
    print('\n[Finished]')
