name: root
channels:
  - pytorch
  - conda-forge
dependencies:
  - pip=21.1
  - python=3.8
  - ros-rospy
  - pip:
    - opencv-python>=4.3.0.36
    - networkx
    - scikit-image
    - gym>=0.17.2
    - tabulate
    - PyYAML
    - tabulate
    - psutil
    - Rx==3.2.0
    - termcolor
    - defusedxml
    - netifaces
    - pyglet
    - sphinx_autodoc_typehints
    - sphinx>=4.2
    # See https://github.com/readthedocs/sphinx_rtd_theme/issues/1115
    - sphinx_rtd_theme>=1.0
