node_type: eagerx_bridge_openai_gym.simnodes/ObservationSensor
default:
  rate:
  inputs: [tick]
  outputs: [observation]
  process: 2  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'

inputs:
  tick:
    msg_type: std_msgs.msg/UInt64
    window: 0

outputs:
  observation:
    msg_type: std_msgs.msg/Float32MultiArray